PHRASE = "To be or not to be."

COLOR_MODEL = "RGB"
IMAGE_SIZE = (225, 225)

# POPULATION_SIZE = 6394400
POPULATION_SIZE = 250
CROSSOVER_PROBABILITY = 1
MUTATION_PROBABILITY = 0.2

ICON__PATH = "..\images\earth.jpg"
IMAGE_PATH = "..\images\earth.jpg"
OPEN_FILE_MODE = "r"

FRAME_SIZE = (470, 263)
IMAGES_RATIO = 0.5
