COLOR_MODEL = "RGB"
IMAGE_SIZE = (225, 225)

POPULATION_SIZE = 100
GENERATIONS = 200
CROSSOVER_PROBABILITY = 0.9
MUTATION_PROBABILITY = 0.25
MAX_GENE_NUMBER = 255
MIN_GENE_NUMBER = 0

ICON__PATH = "..\images\earth.jpg"
IMAGE_PATH = "..\images\earth.jpg"
OPEN_FILE_MODE = "r"

FRAME_SIZE = (470, 263)
IMAGES_RATIO = 0.5
